apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod
  region: eu-west-1

#Update this if you wish to use existing VPC
# vpc:
#   subnets:
#     private:
#       eu-north-1a: { id: subnet-0ff156e0c4a6d300c }
#       eu-north-1b: { id: subnet-0549cdab573695c03 }
#       eu-north-1c: { id: subnet-0426fb4a607393184 }

#For self managedNodeGroups edit following:

# nodeGroups:
#   - name: ng-1-workers
#     labels: { role: workers }
#     instanceType: m5.xlarge
#     desiredCapacity: 10
#     privateNetworking: true
#

# Examples for other samples can be viewed here: https://github.com/weaveworks/eksctl/tree/main/examples


managedNodeGroups:
  - name: prod-ng-1
    instanceType: t3.large
    desiredCapacity: 3
